using Acrelec.SCO.Core.Interfaces;
using Acrelec.SCO.Core.Managers;
using Acrelec.SCO.Core.Providers;
using Acrelec.SCO.DataStructures;
using System;
using System.Threading.Tasks;

namespace Acrelec.SCO.Core
{
    class Program
    {
        static async Task Main(string[] args)
        {
            Console.WriteLine("SCO - Self Check Out System");

            //init
            IItemsProvider itemsProvider = new ItemsProvider();
            IOrderManager orderManager = new OrderManager(itemsProvider);

            //list POS items
            ListAllItems();

            //todo - check if server is available for order injection

            //todo - create an order containing the following items:
            //1*Coke
            //2*Water
            var newOrder = new Order();
            //...            

            //inject the order to POS
            var assignedOrderNumber = await orderManager.InjectOrderAsync(newOrder);

            if (string.IsNullOrWhiteSpace(assignedOrderNumber))
                Console.WriteLine("Order injected with success");
            else
                Console.WriteLine("Error injecting order");

            Console.ReadLine();
        }

        /// <summary>
        /// list in Console all items (with all their properties)
        /// </summary>
        private static void ListAllItems()
        {
            //todo - list items and for each item a short code generated by the POSItemExtensions
        }
    }
}
